repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      exclude: ^archive/
      language_version: python3.8
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.260'
  hooks:
    - id: ruff